<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>FengshaSaveEditor</AssemblyName>
    <RootNamespace>FengshaSaveEditor</RootNamespace>
    <ApplicationIcon Condition="Exists('Assets\fengsha-game.ico')">Assets\fengsha-game.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Assets\donation-alipay.jpg" Condition="Exists('Assets\donation-alipay.jpg')" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    <None Include="Assets\donation-wechat.png" Condition="Exists('Assets\donation-wechat.png')" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>
</Project>
